title: "Mamadou DIEDHIOU"
theme: jekyll-theme-cayman
lang: fr

url: "https://mamadou-data.github.io"
baseurl: "/My-Page"

github:
  is_project_page: true
  repository_url: "https://github.com/mamadou-data/My-Page"
