title: "Mamadou DIEDHIOU"
description: "Data Analyst Portfolio"
theme: jekyll-theme-minimal
show_downloads: true
lang: fr

# Logo / photo affichée en haut (mets ton image dans /assets/img/)
logo: img/mypicture.jpg

# Liens utiles (affichés selon le thème)
github:
  is_project_page: true
  repository_url: https://github.com/douboym
